# Start with a base image containing Java runtime
FROM openjdk-19.0.1

# Add Maintainer Info
MAINTAINER Waldon

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 80 available to the world outside this container
EXPOSE 80

# The application's jar file
ARG JAR_FILE=target/GraduateRecruitmentPortalAPI-1.0-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} GraduateRecruitmentPortalAPI-1.0-SNAPSHOT.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/GraduateRecruitmentPortalAPI-1.0-SNAPSHOT.jar"]